DROP TABLE REPORTCONTENT;
DROP TABLE USERQUEUELIST;
DROP TABLE THREADVOTE;
DROP TABLE COMMENTVOTE;
DROP TABLE THREADCOMMENT;
DROP TABLE USERTHERAPIST;
DROP TABLE MESSAGE;
DROP TABLE THREADIMAGE;
DROP TABLE THREAD;
DROP TABLE DIARYENTRY;
DROP TABLE FOCUSSESSION;
DROP TABLE PLAYLISTMUSIC;
DROP TABLE USERPLAYLIST;
DROP TABLE USERFAVOURITE;
DROP TABLE USERBADGE;
DROP TABLE ACHIEVEMENTREWARD;
DROP TABLE USERINVENTORYITEM;
DROP TABLE USERACHIEVEMENT;
DROP TABLE RESPONSE;
DROP TABLE LANDCONTENT;
DROP TABLE LAND;
DROP TABLE BIOME;
DROP TABLE USERTASKLIST;
DROP TABLE RARITYDROPRATE;
DROP TABLE LEVELREWARD;
DROP TABLE USERLEVEL;
DROP TABLE TASK;
DROP TABLE MUSIC;
DROP TABLE QUESTION;
DROP TABLE TREE;
DROP TABLE TREERARITY;
DROP TABLE TREEBOX;
DROP TABLE ITEM;
DROP TABLE ACHIEVEMENT;
DROP TABLE ACHIEVEMENTCATEGORY;
DROP TABLE BADGE;
DROP TABLE TOKEN;
DROP TABLE CALLSESSION;
DROP TABLE APPOINTMENT;
DROP TABLE TIMESLOT;
DROP TABLE THERAPIST;
DROP TABLE THREADCATEGORY;
DROP TABLE USERS;



-- ANDREW CHECKED ///////
CREATE TABLE USERS(
    USERID           CHAR(8)         NOT NULL,
    USERNAME         VARCHAR(100)    NOT NULL,
    USERPW           VARCHAR(20)     NOT NULL,
    USEREMAIL        VARCHAR(100)    NOT NULL UNIQUE,
    USERBIRTHDAY     DATE            NOT NULL,
    COINS            INT DEFAULT 500 NOT NULL,
    EXP              INT DEFAULT 0   NOT NULL,
    LOGINSTREAK          INT DEFAULT 1   NOT NULL,
    USERLEVEL        INT DEFAULT 0   NOT NULL,
    PITY             INT DEFAULT 0 NOT NULL,
    LASTLOGINDATE    DATE  DEFAULT CURRENT_DATE NOT NULL,
    DIARYVISIBILITY  BOOLEAN         NOT NULL DEFAULT TRUE,
    FORESTVISIBILITY BOOLEAN         NOT NULL DEFAULT TRUE,
    ISDELETED        BOOLEAN         NOT NULL DEFAULT FALSE,
    USERIMAGE        VARCHAR(100),
    PRIMARY KEY(USERID)
);


-- JIANHUI CHECKED ///////
CREATE TABLE BADGE(
    BADGEID     CHAR(8)         NOT NULL,
    BADGENAME   VARCHAR(100)    NOT NULL,
    ISDELETED   BOOLEAN         NOT NULL DEFAULT FALSE,
    BADGEIMAGE  VARCHAR(200) NOT NULL,
    PRIMARY KEY(BADGEID)
);

-- JIANHUI CHECKED ///////
CREATE TABLE ACHIEVEMENTCATEGORY(
    ACHIEVEMENTCATEGORYID   CHAR(8)         NOT NULL,
    ACHIEVEMENTCATEGORYNAME VARCHAR(100)    NOT NULL,
    BADGEID                 CHAR(8)         NOT NULL,
    ISDELETED       				BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(ACHIEVEMENTCATEGORYID),
    FOREIGN KEY(BADGEID) REFERENCES BADGE(BADGEID)
);

-- ANDREW CHECKED ///////
CREATE TABLE ACHIEVEMENT(
    ACHIEVEMENTID           CHAR(8)         NOT NULL,
    ACHIEVEMENTCATEGORYID   CHAR(8)         NOT NULL,
    ACHIEVEMENTNAME         VARCHAR(100)    NOT NULL,
    ACHIEVEMENTDESCRIPTION  VARCHAR(200)    NOT NULL,
    HIDDEN                  BOOLEAN         NOT NULL DEFAULT FALSE,
    ISDELETED      					BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(ACHIEVEMENTID),
    FOREIGN KEY(ACHIEVEMENTCATEGORYID) REFERENCES ACHIEVEMENTCATEGORY(ACHIEVEMENTCATEGORYID)
);

-- ANDREW CHECKED ///////
CREATE TABLE ITEM(
    ITEMID      CHAR(8)         NOT NULL,
    ITEMNAME    VARCHAR(100)    NOT NULL,
    ITEMTYPE    VARCHAR(100)    NOT NULL,
    ITEMSTATUS  BOOLEAN         NOT NULL DEFAULT TRUE,
    ITEMCOST    INT             NOT NULL,
    ISARCHIVED  BOOLEAN         NOT NULL DEFAULT FALSE,
    ISDELETED   BOOLEAN         NOT NULL DEFAULT FALSE,
    ITEMIMAGE   VARCHAR(200) NOT NULL,
    PRIMARY KEY(ITEMID)
);

-- IANHUI CHECKED ///////
CREATE TABLE TREEBOX(
    TREEBOXID       CHAR(8)         NOT NULL,
    TREEBOXNAME     VARCHAR(100)    NOT NULL,
    TREEBOXCOST     INT             NOT NULL,
ISARCHIVED  BOOLEAN         NOT NULL DEFAULT FALSE,
    ISDELETED       BOOLEAN         NOT NULL DEFAULT FALSE,
    TREEBOXIMAGE    VARCHAR(200) NOT NULL,
    PRIMARY KEY(TREEBOXID)
);

-- ANDREW CHECKED ///////
CREATE TABLE TREERARITY(
    RARITYID        CHAR(8)         NOT NULL,
    RARITYNAME      VARCHAR(100)    NOT NULL,
    RARITYCOLOUR    CHAR(7)         NOT NULL,
    ISARCHIVED      BOOLEAN         NOT NULL DEFAULT FALSE,
    ISDELETED       BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(RARITYID)
);

-- ANDREW CHECKED ///////
CREATE TABLE TREE(
    TREEID          CHAR(8)      NOT NULL,
    RARITYID        CHAR(8)      NOT NULL,
    TREENAME        VARCHAR(100) NOT NULL,
    TREEDESCRIPTION VARCHAR(300) NOT NULL,
    ISARCHIVED      BOOLEAN      NOT NULL DEFAULT FALSE,
    TREESTATUS      BOOLEAN      NOT NULL DEFAULT TRUE,
    ISDELETED       BOOLEAN      NOT NULL DEFAULT FALSE,
    TREEIMAGE       VARCHAR(200) NOT NULL,
    PRIMARY KEY(TREEID),
    FOREIGN KEY(RARITYID) REFERENCES TREERARITY(RARITYID)
);

-- JIANHUI CHECKED ///////
CREATE TABLE QUESTION(
    QUESTIONID          CHAR(8)      NOT NULL,
    QUESTIONDESCRIPTION VARCHAR(100) NOT NULL,
    ISDELETED           BOOLEAN      NOT NULL DEFAULT FALSE,
    ISARCHIVED          BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY(QUESTIONID)
);

-- HUAIERN CHECKED ///////
CREATE TABLE MUSIC (
    MUSICID     CHAR(8)      NOT NULL,
    MUSICNAME   VARCHAR(100) NOT NULL,
    AUTHOR      VARCHAR(200) NOT NULL,
    FILEPATH    VARCHAR(200) NOT NULL,
    MHOUR       INT          NOT NULL,
    MMINUTE     INT          NOT NULL,
    MSECOND     INT          NOT NULL,
    ISDELETED   BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(MUSICID)
);

-- HUAIERN CHECKED ///////
CREATE TABLE THERAPIST(
    THERAPISTID     CHAR(8)      NOT NULL,
    THERAPISTNAME   VARCHAR(100) NOT NULL,
    THERAPISTPW     VARCHAR(20)  NOT NULL,
    THERAPISTEMAIL  VARCHAR(100) NOT NULL,
  	AREAOFINTEREST	VARCHAR(200) NOT NULL,
  	LANGUAGESPOKEN	VARCHAR(200) NOT NULL,
  	YEAROFEXP				INT					 NOT NULL,
  	CULTURE					VARCHAR(20)	 NOT NULL,
    THERAPISTSTATUS BOOLEAN      NOT NULL DEFAULT TRUE,
    ISDELETED       BOOLEAN      NOT NULL DEFAULT FALSE,
    THERAPISTIMAGE BLOB,
    PRIMARY KEY(THERAPISTID)
);

-- HUAIERN CHECKED //////
CREATE TABLE TASK(
    TASKID           CHAR(8)         NOT NULL,
    TASKNAME         VARCHAR(100)    NOT NULL,
    TASKDESCRIPTION  VARCHAR(300)    NOT NULL,
    ISCUSTOMISABLE   BOOLEAN         NOT NULL,
    ISARCHIVED       BOOLEAN         NOT NULL DEFAULT FALSE,
    ISDELETED        BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(TASKID)
);

-- JIANHUI CHECKED ///////
CREATE TABLE USERLEVEL(
    LEVELID     INT     NOT NULL,
    REQUIREDXP  INT     NOT NULL,
    ISDELETED   BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(LEVELID)
);

-- CHOONCHONG CHECKED ///////
CREATE TABLE LEVELREWARD(
    LEVELREWARDID   CHAR(8)		NOT NULL,
    LEVELID         INT				NOT NULL,
    TREEBOXID       CHAR(8),
    ITEMID          CHAR(8),
    QUANTITY        INT				NOT NULL,
    ISDELETED       BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(LEVELREWARDID),
    FOREIGN KEY(LEVELID)    REFERENCES USERLEVEL(LEVELID),
    FOREIGN KEY(TREEBOXID)  REFERENCES TREEBOX(TREEBOXID),
    FOREIGN KEY(ITEMID)     REFERENCES ITEM(ITEMID)
);

-- JIANHUI CHECKED //////
    CREATE TABLE RARITYDROPRATE(
    TREEBOXID   CHAR(8)      NOT NULL,
    RARITYID    CHAR(8) 		 NOT NULL,
    PERCENTAGE  DECIMAL(4,2) NOT NULL,
    ISDELETED   BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(TREEBOXID, RARITYID),
    FOREIGN KEY(TREEBOXID)  REFERENCES TREEBOX(TREEBOXID),
    FOREIGN KEY(RARITYID)   REFERENCES TREERARITY(RARITYID)
);

-- HUAIERN CHECKED ///////
CREATE TABLE USERTASKLIST (
    USERTASKLISTID              CHAR(8)      NOT NULL,
    TASKID                      CHAR(8)      NOT NULL,
    USERID                      CHAR(8)      NOT NULL,
    CUSTOMISEDTASKNAME          VARCHAR(100),
    CUSTOMISEDTASKDESCRIPTION   VARCHAR(300),
    DATETIMEACCEPTED            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATECOMPLETED               TIMESTAMP,
    ISDELETED       						BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(USERTASKLISTID),
    FOREIGN KEY(TASKID) REFERENCES TASK(TASKID),
    FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);

-- ANDREW CHECKED /////./
CREATE TABLE BIOME(
    BIOMEID          CHAR(8)        NOT NULL,
    BIOMENAME        VARCHAR(100)   NOT NULL,
    BIOMEDESCRIPTION VARCHAR(300)   NOT NULL,
    BIOMECOST        INT            NOT NULL,
    ISDELETED        BOOLEAN        NOT NULL DEFAULT FALSE,
    ISARCHIVED       BOOLEAN        NOT NULL DEFAULT FALSE,
    BIOMEIMAGE       VARCHAR(200) NOT NULL,
    PRIMARY KEY(BIOMEID)
);

-- JIANHUI CHECKED/////
CREATE TABLE LAND(
    LANDID      CHAR(8)         NOT NULL,
    USERID      CHAR(8)         NOT NULL,
    BIOMEID     CHAR(8)         NOT NULL,
    LANDNAME    VARCHAR(100)    NOT NULL,
    ISMAINLAND  BOOLEAN         NOT NULL,
    ISDELETED   BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(LANDID),
    FOREIGN KEY(USERID)  REFERENCES USERS(USERID),
    FOREIGN KEY(BIOMEID) REFERENCES BIOME(BIOMEID)
);

-- HUAIERN CHECKED /////
CREATE TABLE LANDCONTENT(
    LANDCONTENTID    CHAR(8) NOT NULL,
    LANDID           CHAR(8) NOT NULL,
    ITEMID           CHAR(8),
    TREEID           CHAR(8),
    XCOORD           INT     NOT NULL,
    YCOORD           INT     NOT NULL,
    ISDELETED        BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(LANDCONTENTID),
    FOREIGN KEY(LANDID) REFERENCES LAND(LANDID),
    FOREIGN KEY(ITEMID) REFERENCES ITEM(ITEMID),
    FOREIGN KEY(TREEID) REFERENCES TREE(TREEID)
);

-- JIANHUI CHECKED//////
CREATE TABLE RESPONSE(
    RESPONSEID           CHAR(8)      NOT NULL,
    USERID               CHAR(8)      NOT NULL,
    QUESTIONID           CHAR(8)      NOT NULL,
    RESPONSEDESCRIPTION  VARCHAR(400) NOT NULL,
    ISARCHIVED           BOOLEAN      NOT NULL DEFAULT FALSE,
    ISDELETED       		 BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(RESPONSEID),
    FOREIGN KEY(USERID)     REFERENCES USERS(USERID),
    FOREIGN KEY(QUESTIONID) REFERENCES QUESTION(QUESTIONID)
);

-- ANDREWW CHECKED ///////
CREATE TABLE USERACHIEVEMENT(
    USERID        CHAR(8) NOT NULL,
    ACHIEVEMENTID CHAR(8) NOT NULL,
    DATECOMPLETED DATE    NOT NULL DEFAULT CURRENT_DATE,
    ISDELETED     BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(USERID, ACHIEVEMENTID),
    FOREIGN KEY(USERID)          REFERENCES USERS(USERID),
    FOREIGN KEY(ACHIEVEMENTID)   REFERENCES ACHIEVEMENT(ACHIEVEMENTID)
);

-- ANDREW CHECKED//////
 CREATE TABLE USERINVENTORYITEM(
    INVENTORYITEMID CHAR(8) NOT NULL,
    USERID          CHAR(8) NOT NULL, 
    TREEBOXID       CHAR(8), 
    ITEMID          CHAR(8),
   	TREEID					CHAR(8),
   	BIOMEID					CHAR(8),
    QUANTITY        INT     NOT NULL,
    ISDELETED       BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(INVENTORYITEMID),
    FOREIGN KEY(USERID)     REFERENCES USERS(USERID),
    FOREIGN KEY(TREEBOXID)  REFERENCES TREEBOX(TREEBOXID),
    FOREIGN KEY(ITEMID)     REFERENCES ITEM(ITEMID),
   	FOREIGN KEY(TREEID)			REFERENCES TREE(TREEID),
   	FOREIGN KEY(BIOMEID)		REFERENCES BIOME(BIOMEID)
);

-- JIANHUI CHECKED//////
CREATE TABLE ACHIEVEMENTREWARD(
    ACHIEVEMENTREWARDID CHAR(8) NOT NULL,
    ACHIEVEMENTID       CHAR(8) NOT NULL,
    TREEBOXID           CHAR(8),
    ITEMID              CHAR(8),
    QUANTITY            INT     NOT NULL,
    ISDELETED       		BOOLEAN         NOT NULL DEFAULT FALSE,
PRIMARY KEY(ACHIEVEMENTREWARDID),
FOREIGN KEY(ACHIEVEMENTID) REFERENCES ACHIEVEMENT(ACHIEVEMENTID),
FOREIGN KEY(TREEBOXID)     REFERENCES TREEBOX(TREEBOXID),
FOREIGN KEY(ITEMID)        REFERENCES ITEM(ITEMID)
);

-- JIANHUI CHECKED////
CREATE TABLE USERBADGE(
    USERID     CHAR(8) NOT NULL,
    BADGEID    CHAR(8) NOT NULL,
    ISSELECTED BOOLEAN NOT NULL DEFAULT FALSE,
    ISDELETED  BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY(USERID, BADGEID),
    FOREIGN KEY(USERID)  REFERENCES USERS(USERID),
    FOREIGN KEY(BADGEID) REFERENCES BADGE(BADGEID)
);

-- HUAIERN CHECKED//////
CREATE TABLE USERFAVOURITE(
    USERID    CHAR(8) NOT NULL,
    MUSICID   CHAR(8) NOT NULL,
    ISDELETED BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(USERID, MUSICID),
    FOREIGN KEY (USERID)  REFERENCES USERS(USERID),
    FOREIGN KEY (MUSICID) REFERENCES MUSIC(MUSICID)
);

-- HUAIERN CHECKED//////
CREATE TABLE USERPLAYLIST(
    PLAYLISTID   CHAR(8)     NOT NULL,
    USERID       CHAR(8)     NOT NULL,
    PLAYLISTNAME VARCHAR(50) NOT NULL,
    DATECREATED  DATE        NOT NULL DEFAULT CURRENT_DATE,
    ISDELETED    BOOLEAN     NOT NULL DEFAULT FALSE,
    PRIMARY KEY (PLAYLISTID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

-- JIANHUI CHECKED/////
CREATE TABLE PLAYLISTMUSIC(
    PLAYLISTID CHAR(8) NOT NULL,
    MUSICID    CHAR(8) NOT NULL,
    ISDELETED  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(PLAYLISTID, MUSICID),
    FOREIGN KEY(PLAYLISTID) REFERENCES USERPLAYLIST(PLAYLISTID),
    FOREIGN KEY(MUSICID) REFERENCES MUSIC(MUSICID)
);

-- JIANHUI CHECKED//////
CREATE TABLE FOCUSSESSION (
    SESSIONID          CHAR(8)      NOT NULL,
    USERID             CHAR(8)      NOT NULL,
    SESSIONTYPE        VARCHAR(20)  NOT NULL,
    DURATION           DECIMAL(6,2) NOT NULL,
    POMODOROMINORBREAK INT,
    POMODOROMAJORBREAK INT,
    SESSIONSTATUS      VARCHAR(20)  NOT NULL,
    TREEBOXESOBTAINED  INT          NOT NULL,
    ISDELETED       	 BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (SESSIONID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

-- JIAQUANN CHECKED //////
CREATE TABLE DIARYENTRY(
    DIARYID      CHAR(8)     NOT NULL,
    USERID       CHAR(8)     NOT NULL,
    DIARYTITLE   VARCHAR(50),
    DESCRIPTION  VARCHAR(400),
    MOOD         VARCHAR(50),
    DATEWRITTEN  DATE        NOT NULL DEFAULT CURRENT_DATE,
    ISARCHIVED   BOOLEAN     NOT NULL DEFAULT FALSE,
    ISDELETED    BOOLEAN     NOT NULL DEFAULT FALSE,
    PRIMARY KEY(DIARYID),
    FOREIGN KEY(USERID) REFERENCES USERS(USERID)
);

-- andrew
CREATE TABLE THREADCATEGORY(
	THREADCATEGORYID    CHAR(8)      NOT NULL,
  THREADCATEGORYNAME 	VARCHAR(100) NOT NULL,
  ISDELETED           BOOLEAN      NOT NULL DEFAULT FALSE,
  PRIMARY KEY(THREADCATEGORYID)
);

-- HUAIERN CHECKED/////
CREATE TABLE THREAD (
    THREADID             CHAR(8)         NOT NULL,
    USERID               CHAR(8)         NOT NULL,
  	THREADCATEGORYID			CHAR(8)				 NOT NULL,
    THREADTITLE          VARCHAR(100)    NOT NULL,
    THREADDESCRIPTION    VARCHAR(1000)   NOT NULL,
    UPVOTE               INT             NOT NULL,
    DOWNVOTE             INT             NOT NULL,
    SHARECOUNT           INT             NOT NULL,
    ISDELETED            BOOLEAN         NOT NULL DEFAULT FALSE,
    PRIMARY KEY (THREADID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
  	FOREIGN KEY (THREADCATEGORYID) REFERENCES THREADCATEGORY(THREADCATEGORYID)
);



-- HUAIERN CHECKED/////
CREATE TABLE THREADIMAGE(
    IMAGEID     CHAR(8) NOT NULL,
    THREADID    CHAR(8) NOT NULL,
    ISMAINIMAGE BOOLEAN NOT NULL DEFAULT FALSE,
    ISDELETED   BOOLEAN NOT NULL DEFAULT FALSE,
    IMAGE       VARCHAR(255),
    PRIMARY KEY(IMAGEID,THREADID),
    FOREIGN KEY(THREADID) REFERENCES THREAD(THREADID)
);

-- JIAQUANN CHECKED/////
CREATE TABLE THREADCOMMENT (
    THREADCOMMENTID     CHAR(8)      NOT NULL,
    THREADID            CHAR(8)      NOT NULL,
    USERID              CHAR(8)      NOT NULL,
    COMMENTIDREPLYINGTO CHAR(8),
    POSTDATETIME        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONTENT             VARCHAR(500) NOT NULL,
    UPVOTE              INT          NOT NULL,
    DOWNVOTE            INT          NOT NULL,
    ISDELETED           BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (THREADCOMMENTID),
    FOREIGN KEY (THREADID) REFERENCES THREAD(THREADID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    FOREIGN KEY (COMMENTIDREPLYINGTO) REFERENCES THREADCOMMENT(THREADCOMMENTID)
);

-- ANDREW CHECKED/////
CREATE TABLE USERTHERAPIST(
    USERTHERAPISTID CHAR(8) NOT NULL,
    USERID          CHAR(8) NOT NULL,
    THERAPISTID     CHAR(8) NOT NULL,
    DATEESTABLISHED DATE    NOT NULL,
    DATEEND         DATE,
    ISDELETED       BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(USERTHERAPISTID),
    FOREIGN KEY(USERID)      REFERENCES USERS(USERID),
    FOREIGN KEY(THERAPISTID) REFERENCES THERAPIST(THERAPISTID)
);

-- ANDREW CHECKED/////
CREATE TABLE MESSAGE(
    MESSAGEID       CHAR(8)      NOT NULL,
    USERID          CHAR(8)      NOT NULL,
    THERAPISTID     CHAR(8)      NOT NULL,
    SENDER          VARCHAR(15)  NOT NULL,
    CONTENT         VARCHAR(400) NOT NULL,
    TIMESTAMPSENT   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIMESTAMPREAD   TIMESTAMP,
    ISDELETED       BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY(MESSAGEID),
    FOREIGN KEY(USERID)      REFERENCES USERS(USERID),
    FOREIGN KEY(THERAPISTID) REFERENCES THERAPIST(THERAPISTID)
);

-- JIAQUANN  CHECKED/////
CREATE TABLE TIMESLOT (
    TIMESLOTID  CHAR(8) NOT NULL,
    THERAPISTID CHAR(8) NOT NULL,
    TSDATE      DATE,
    STARTTIME   TIME,
    ENDTIME     TIME,
    STATUS      BOOLEAN NOT NULL DEFAULT TRUE,
    ISDELETED   BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (TIMESLOTID),
    FOREIGN KEY (THERAPISTID) REFERENCES THERAPIST(THERAPISTID)
);

-- JIAQUANN  CHECKED/////
CREATE TABLE APPOINTMENT (
    APPOINTMENTID   CHAR(8)      NOT NULL,
    USERID          CHAR(8)      NOT NULL,
    TIMESLOTID      CHAR(8)      NOT NULL,
    APPOINTMENTLINK VARCHAR(100),
    STATUS          VARCHAR(20),
    LINKSENT        BOOLEAN      NOT NULL DEFAULT FALSE,
    ISDELETED       BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (APPOINTMENTID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    FOREIGN KEY (TIMESLOTID) REFERENCES TIMESLOT(TIMESLOTID)
);

-- JIAQUANN CHECKED/////
CREATE TABLE CALLSESSION (
    CALLSESSIONID CHAR(8) NOT NULL,
    APPOINTMENTID CHAR(8) NOT NULL,
    DURATION      INT,
    ISDELETED     BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (CALLSESSIONID),
    FOREIGN KEY (APPOINTMENTID) REFERENCES APPOINTMENT(APPOINTMENTID)
);

-- JIAQUANN  CHECKED/////
CREATE TABLE TOKEN (
    TOKENID VARCHAR(100) NOT NULL,
    EXPIRE    TIMESTAMP NOT NULL,
    USERID    CHAR(8)   NOT NULL,
    ISDELETED BOOLEAN   NOT NULL DEFAULT FALSE,
    PRIMARY KEY (TOKENID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);


-- NEW TABLES
CREATE TABLE THREADVOTE(
		THREADID CHAR(8) NOT NULL,
  	USERID CHAR(8) NOT NULL,
  	VOTETYPE BOOLEAN NOT NULL,
  	PRIMARY KEY (THREADID, USERID),
  	FOREIGN KEY (THREADID) REFERENCES THREAD (THREADID),
  	FOREIGN KEY (USERID) REFERENCES USERS (USERID)
);

CREATE TABLE COMMENTVOTE(
		THREADCOMMENTID CHAR(8) NOT NULL,
  	USERID CHAR(8) NOT NULL,
  	VOTETYPE BOOLEAN NOT NULL,
  	PRIMARY KEY (THREADCOMMENTID, USERID),
  	FOREIGN KEY(THREADCOMMENTID) REFERENCES THREADCOMMENT (THREADCOMMENTID),
  	FOREIGN KEY(USERID) REFERENCES USERS (USERID)
);

CREATE TABLE USERQUEUELIST(
       USERID CHAR(8) NOT NULL,
       MUSICID CHAR(8) NOT NULL,
       PRIMARY KEY (USERID, MUSICID),
       FOREIGN KEY (USERID) REFERENCES USERS(USERID),
       FOREIGN KEY (MUSICID) REFERENCES MUSIC(MUSICID)

);

CREATE TABLE REPORTCONTENT(
  	REPORTCONTENTID CHAR(8) NOT NULL,
  	USERID          CHAR(8) NOT NULL,
  	THREADID        CHAR(8),
  	THREADCOMMENTID CHAR(8),
  	REPORTREASON    VARCHAR(255),
  	ISSOLVED        BOOLEAN NOT NULL DEFAULT FALSE,
  	PRIMARY KEY (REPORTCONTENTID),
  	FOREIGN KEY(USERID) REFERENCES USERS(USERID),
  	FOREIGN KEY(THREADID) REFERENCES THREAD(THREADID),
  	FOREIGN KEY(THREADCOMMENTID) REFERENCES THREADCOMMENT (THREADCOMMENTID)
);
